# Generated by Django 2.0.5 on 2018-05-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='quantity_stock',
            field=models.FloatField(default=0),
        ),
    ]
