# Generated by Django 2.0 on 2018-04-22 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0012_auto_20180422_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='tax_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='price',
            name='tax_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ERP.TaxGroup'),
        ),
        migrations.AddField(
            model_name='pricelog',
            name='tax_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pricelog',
            name='tax_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ERP.TaxGroup'),
        ),
    ]
