# Generated by Django 2.0 on 2018-04-23 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ERP', '0014_auto_20180422_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField()),
                ('series', models.CharField(default=None, max_length=100)),
                ('supplier_bill_no', models.CharField(default=None, max_length=100)),
                ('purpose', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('bill_amount', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('tax_amount', models.FloatField(default=0)),
                ('net_amount', models.FloatField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ERP.Company')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Purchase_Created_By_User', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Purchase_Modified_By_User', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP.Supplier')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP.WareHouse')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseInvoice_Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField(default=0)),
                ('rate', models.FloatField(default=0)),
                ('bill_amount', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('tax_per', models.FloatField(default=0)),
                ('tax_amount', models.FloatField(default=0)),
                ('net_amount', models.FloatField(default=0)),
                ('batchno', models.CharField(default=None, max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ERP.Company')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='PurchaseInvoice_items_Created_By_User', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.Item')),
                ('modified_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='PurchaseInvoice_items_Modified_By_User', to=settings.AUTH_USER_MODEL)),
                ('purchaseinvoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.PurchaseInvoice')),
                ('taxgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP.TaxGroup')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP.WareHouse')),
            ],
        ),
        migrations.CreateModel(
            name='TaxSplitup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.IntegerField(default=0)),
                ('ref_type', models.IntegerField(default=0)),
                ('tax_per', models.FloatField(default=0)),
                ('tax_amount', models.FloatField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ERP.Company')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='TaxSplitup_Created_By_User', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='TaxSplitup_Modified_By_User', to=settings.AUTH_USER_MODEL)),
                ('tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP.Tax')),
                ('taxgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP.TaxGroup')),
            ],
        ),
    ]
