# Generated by Django 2.0 on 2018-05-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0017_auto_20180425_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='item_discount',
            field=models.FloatField(default=0),
        ),
    ]
