# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-03 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0018_purchaseinvoice_item_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='bill_amount_before_tax',
            field=models.FloatField(default=0),
        ),
    ]
