# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-05 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0019_purchaseinvoice_bill_amount_before_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice_items',
            name='bill_amount_before_tax',
            field=models.FloatField(default=0),
        ),
    ]
