# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-13 13:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ERP', '0020_purchaseinvoice_items_bill_amount_before_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salesinvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_date', models.DateTimeField()),
                ('series', models.CharField(default=None, max_length=100)),
                ('bill_mode', models.IntegerField(default=0)),
                ('bill_type', models.IntegerField(default=0)),
                ('bill_amount', models.FloatField(default=0)),
                ('item_discount', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('bill_amount_before_tax', models.FloatField(default=0)),
                ('tax_amount', models.FloatField(default=0)),
                ('net_amount', models.FloatField(default=0)),
                ('paid_amount', models.FloatField(default=0)),
                ('balance_amount', models.FloatField(default=0)),
                ('credit_date', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ERP.Company')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sales_Created_By_User', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP.Customer')),
                ('modified_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='aales_Modified_By_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoice_Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField(default=0)),
                ('rate', models.FloatField(default=0)),
                ('bill_amount', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('tax_per', models.FloatField(default=0)),
                ('bill_amount_before_tax', models.FloatField(default=0)),
                ('tax_amount', models.FloatField(default=0)),
                ('net_amount', models.FloatField(default=0)),
                ('batchno', models.CharField(default=None, max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ERP.Company')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='salesInvoice_items_Created_By_User', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.Item')),
                ('modified_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='salesInvoice_items_Modified_By_User', to=settings.AUTH_USER_MODEL)),
                ('purchaseinvoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.Salesinvoice')),
                ('taxgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP.TaxGroup')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP.WareHouse')),
            ],
        ),
    ]
