# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-13 22:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0021_salesinvoice_salesinvoice_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesinvoice_items',
            old_name='purchaseinvoice',
            new_name='sales_invoice',
        ),
    ]
