# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-13 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0022_auto_20180513_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice_items',
            name='batchno',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
