# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-20 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0025_auto_20180518_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxsplitup',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP.Item'),
        ),
    ]
