# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-20 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0026_taxsplitup_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='bill_payment_type',
            field=models.FloatField(default=0),
        ),
    ]
