# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-20 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0027_salesinvoice_bill_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='default_cash_customer',
            field=models.IntegerField(default=0),
        ),
    ]
